version: '3'

services:
  youth-permission-api:
    build: .
    container_name: youth-permission-api
    restart: always
    environment:
      VIRTUAL_HOST: api.yourdomain.com
      LETSENCRYPT_HOST: api.yourdomain.com
      LETSENCRYPT_EMAIL: you@email.com
    depends_on:
      - mysql-db

networks:
  default:
    external:
      name: proxy-tier
  backend:
    external: true
