version: "3.9"

services:
  traefik:
    image: traefik:v2.11
    container_name: youth_traefik_test
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # If you want HTTPS with Let's Encrypt later, we can add it.
    ports:
      - "80:80"
      - "443:443"
      # Optional: dashboard (lock this down if you expose it!)
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - youth_net
      
  api:
    image: youth-api
    container_name: youth-api
    environment:
      - ENV=test   # change to "prod" when you want MySQL
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=youth
      - DB_PASSWORD=youthpass
      - DB_NAME=youthdb
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - activity-net

  web:
    image: youth-web
    container_name: youth-web
    environment:
      - ENV=prod   # change to "prod" in production
      - BASE_URL=http://127.0.0.1:8000
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - activity-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.youth-api.rule=Host(`youth-api.lthome.com`)
      - traefik.http.routers.youth-api.entrypoints=web
      - traefik.http.services.youth-api.loadbalancer.server.port=8000


  mysql:
    image: mysql:8.0
    container_name: youth-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: youthdb
      MYSQL_USER: youth
      MYSQL_PASSWORD: youthpass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - activity-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.youth-web.rule=Host(`youth.lthome.com`)
      - traefik.http.routers.youth-web.entrypoints=web
      - traefik.http.services.youth-web.loadbalancer.server.port=80

networks:
  activity-net:
    driver: bridge

volumes:
  mysql_data:
