version: '3'

services:
  website:
    build: .
    container_name: website
    restart: always
    environment:
      VIRTUAL_HOST: yourdomain.com,www.yourdomain.com
      LETSENCRYPT_HOST: yourdomain.com,www.yourdomain.com
      LETSENCRYPT_EMAIL: you@email.com

networks:
  default:
    external:
      name: proxy-tier
